### ISSUE TITLE
`fish` 版本过低导致无法运行脚本

### ISSUE THREAD

**Issue by fleebeatles** [mingcenwei/pku_copyleft#1]
系统为Ubuntu18.04，根据README安装完相应的包，使用fish shell。
运行命令 `./pku_copyleft.fish --cookie '0CA3BD75D283BAD65F88FB4C3A7A91C8' --fid ' 8113a9d6b49fa3a34df0c2aed39d711c'`，提示错误为
![2022-09-18 19-49-08屏幕截图](https://user-images.githubusercontent.com/13066817/190900574-01cab25f-db92-4436-ad67-fadc1b5f3449.png)
将脚本中的3处`||`修改为`or`，1处`&&`修改为`and`后，再次运行，提示为
![2022-09-18 19-52-30屏幕截图](https://user-images.githubusercontent.com/13066817/190900706-13f724c4-535a-4aa4-8157-b26462ebff01.png)

是不是我哪里配置的有问题？

**Comment by mingcenwei** [comment]
应该是 `fish` 的版本太低的缘故，我当前的 `fish` 的版本是 `version 3.5.1`（可以用 `fish --version` 来查看），而你的版本应该才 `2.x.x`。可以先试试在脚本中作以下替换：`&&` 全部换为 `; and`（注意分号），`||` 全部换为`; or`，`PARALLEL_SHELL=(command -v 'fish')` 替换为 `env PARALLEL_SHELL=(command -v 'fish')`

**Comment by fleebeatles** [comment]
@mingcenwei 将`fish`替换为3.5.1版本后，脚本正常运行。感谢！
